version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./conf/proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./content:/usr/share/nginx/html
      # - ./certbot/www/:/var/www/certbot/:ro
      # - ./certbot/conf/:/etc/nginx/ssl/:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    restart: always

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      nginx:
        condition: service_healthy
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw