---
- hosts: all
  become: true
  tasks:
    - name: Copy VueJS app source files
      ansible.builtin.copy:
        src: ../server/content/
        dest: /home/ubuntu/server/content/
    - name: Launch App
      community.docker.docker_compose_v2:
        project_src: ./server/
        files: docker-compose.yml
        build: always
        remove_orphans: true